In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import random

In [9]:
#define dynamic grid
shape = 10
p1 = np.random.uniform(.7,.9)
p0 = 1-p1
grid = np.random.choice([0, 1], p=[p0,p1], size = (shape,shape))
print(type(grid),'\n', grid)



<class 'numpy.ndarray'> 
 [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 0 1 1 1]
 [0 1 1 0 1 1 0 0 1 1]
 [0 1 1 0 1 1 0 1 1 1]
 [1 1 1 1 0 1 1 1 1 1]
 [0 1 0 0 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 0 0 1 1 1 1 0 1 1]
 [1 0 1 1 1 1 1 0 1 1]
 [1 1 1 1 1 1 1 1 1 0]]


In [2]:
actions = ['up', 'down', 'left', 'right']
